name: Deploy
on:
  workflow_dispatch:
  push:
    branches:
      - dev
permissions:
  contents: read
  id-token: write
env:
  RESOURCE_GROUP_NAME: octane-benchmark-rg
  RESOURCE_GROUP_LOCATION: eastus
  STORAGE_JOB_TABLE_NAME: jobs
jobs:
  deploy-infrastructure:
    name: Deploy infrastructure
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v3
      - name: Logon to Azure
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          enable-AzPSSession: true
      - name: Deploy Bicep file
        uses: azure/powershell@v1
        with:
          inlineScript: |
            Set-StrictMode -Version Latest
            $ErrorActionPreference = "Stop"
            $VerbosePreference = "Continue"
            $InformationPreference = "Continue"

            Write-Information "Creating resource group..."
            New-AzResourceGroup -Name "${{ env.RESOURCE_GROUP_NAME }}" -Location "${{ env.RESOURCE_GROUP_LOCATION }}" -Force
            
            Write-Information "Creating resources..."
            $deploymentParameters = @{
              ResourceGroupName = "${{ env.RESOURCE_GROUP_NAME }}"
              TemplateFile = "./bicep/main.bicep"
              TemplateParameterObject = @{
                storageAccountName = "${{ secrets.STORAGE_ACCOUNT_NAME }}"
                storageJobTableName = "${{ env.STORAGE_JOB_TABLE_NAME }}"
              }
            }
            New-AzResourceGroupDeployment @deploymentParameters

            Write-Information "Execution complete."
          azPSVersion: "latest"