name: Deploy
on:
  workflow_dispatch:
  push:
    branches:
      - dev
permissions:
  contents: read
  id-token: write
env:
  RESOURCE_GROUP_NAME: octane-benchmark-rg
  RESOURCE_GROUP_LOCATION: eastus
jobs:
  deploy-infrastructure:
    name: Deploy infrastructure
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v3
      - name: Logon to Azure
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          enable-AzPSSession: true