name: Deploy
on:
  push:
    branches:
      - dev
  workflow_dispatch:
permissions:
  contents: read
  id-token: write
env:
  RESOURCE_GROUP_NAME: octane-benchmark-rg
  RESOURCE_GROUP_LOCATION: eastus
jobs:
  deploy-infrastructure:
    name: Deploy infrastructure
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v3
      - name: Logon to Azure
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          enable-AzPSSession: true
      - name: Deploy Bicep file
        uses: azure/powershell@v1
        with:
          inlineScript: |
            Set-StrictMode -Version Latest
            $ErrorActionPreference = "Stop"
            $VerbosePreference = "Continue"
            $InformationPreference = "Continue"

            Write-Information "Creating resource group..."
            New-AzResourceGroup -Name "${{ env.RESOURCE_GROUP_NAME }}" -Location "${{ env.RESOURCE_GROUP_LOCATION }}" -Force
            
            Write-Information "Creating resources..."
            $deploymentParameters = @{
              ResourceGroupName = "${{ env.RESOURCE_GROUP_NAME }}"
              TemplateFile = "${{ github.workspace}}/bicep/main.bicep"
              TemplateParameterObject = @{
                storageAccountName = "${{ secrets.STORAGE_ACCOUNT_NAME }}"
                serviceBusName = "${{ secrets.SERVICE_BUS_NAME }}"
                logAnalyticsWorkspaceName = "${{ secrets.LOG_ANALYTICS_WORKSPACE_NAME }}"
                applicationInsightsName = "${{ secrets.APPLICATION_INSIGHTS_NAME }}"
                functionAppName = "${{ secrets.FUNCTION_APP_NAME }}"
                appServicePlanName = "${{ secrets.APP_SERVICE_PLAN_NAME }}"
              }
            }
            New-AzResourceGroupDeployment @deploymentParameters

            Write-Information "Execution complete."
          azPSVersion: "latest"
  package-function-app:
    name: Package function app
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v3
      - name: Create function app artifact
        run: |
          set -eu
          echo "Publishing function app..."
          dotnet publish "${{ github.workspace }}/code/functionapp/functionapp.csproj" --configuration Release --output "${{ runner.temp }}/functionapp"
          
          echo "Zipping function app..."
          7z a "${{ runner.temp }}/functionapp.zip" "${{ runner.temp }}/functionapp/*"

          echo "Script complete."
      - name: Publish function app artifact
        uses: actions/upload-artifact@v3
        with:
          name: functionapp
          path: "${{ runner.temp }}/functionapp.zip"
  publish-function-app:
    name: Publish function app
    needs:
      - package-function-app
      - deploy-infrastructure
    runs-on: ubuntu-latest
    steps:
      - name: Download function app artifact
        uses: actions/download-artifact@v3
        with:
          name: functionapp
          path: ${{ runner.temp }}
      - name: Logon to Azure
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      - name: Publish function app
        uses: azure/CLI@v1
        with:
          inlineScript: |
            set -eu
            echo "Deploying function..."
            az functionapp deployment source config-zip --src "${{ runner.temp }}/functionapp.zip" --resource-group "${{ env.RESOURCE_GROUP_NAME }}" --name "${{ secrets.FUNCTION_APP_NAME }}"
            echo "Script complete."